# Generated by Django 4.0.3 on 2023-10-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='vin',
        ),
    ]
