# Generated by Django 4.0.3 on 2023-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
